import assert from "node:assert/strict";import fs from "node:fs";import os from "node:os";import path from "node:path";import test from "node:test";import { parseDistrictMeetingPage, parseMeetingDates } from "../lib/district-meetings.mjs";
import { ebesluitMeetingMonthUrls, parseEbesluitMeetingCalendar } from "../lib/ebesluit-meetings.mjs";import { validateSourceDocument } from "../lib/source-feed.mjs";import { run } from "../scripts/fetch-sources-district-meetings.mjs";
const table=`<p><strong>Data districtsraden en raadscommissies 2026</strong></p><table><tr><th>Data algemene raadscommissie</th><th>Data districtsraad</th><th>Data bijzondere raadscommissies</th></tr><tr><td>maandag 12 oktober</td><td>maandag 19 oktober</td><td>dinsdag 13 oktober en woensdag 14 oktober</td></tr><tr><td>maandag 9 november</td><td>maandag 16 november</td><td>woensdag 18 november</td></tr></table>`;const page={currentVersion:"v1",updatedAt:"2026-09-20T10:00:00Z",snippets:[{id:"abc123def456",type:"wysiwyg",body:{text:table}}]};const response=(json,status=200)=>({ok:status>=200&&status<300,status,json:async()=>json});
test("jaartabel levert raad en commissies",()=>{const p=parseDistrictMeetingPage(page);assert.equal(p.year,2026);assert.deepEqual(p.issues,[]);assert.deepEqual(p.items.map(i=>[i.title,i.date]),[["Algemene raadscommissie Antwerpen","2026-10-12"],["Bijzondere raadscommissie Antwerpen","2026-10-13"],["Bijzondere raadscommissie Antwerpen","2026-10-14"],["Districtsraad Antwerpen","2026-10-19"],["Algemene raadscommissie Antwerpen","2026-11-09"],["Districtsraad Antwerpen","2026-11-16"],["Bijzondere raadscommissie Antwerpen","2026-11-18"]])});
test("weekdagfout wordt niet gegokt",()=>{const p=parseMeetingDates("dinsdag 12 oktober",2026);assert.deepEqual(p.dates,[]);assert.equal(p.issues[0].code,"weekday_mismatch")});
test("ontbrekende planning faalt gesloten",()=>assert.equal(parseDistrictMeetingPage({snippets:[{type:"wysiwyg",body:{text:"<p>Geen planning</p>"}}]}).items.length,0));
test("fetcher schrijft toekomstige vergaderdata",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"district-meetings-"));const s=await run({rootDir:root,clock:()=>new Date("2026-10-10T08:00:00Z"),fetch:async()=>response(page),log:()=>{}});assert.deepEqual([s[0].fetchStatus,s[0].itemCount],["ok",7]);const doc=JSON.parse(fs.readFileSync(path.join(root,"site","sources","district-vergaderingen.json"),"utf8"));assert.deepEqual(validateSourceDocument(doc,{expectedSourceId:"district-vergaderingen"}),[])});

test("meerdere jaartabellen gebruiken elk hun eigen jaartal",()=>{
  const parsed=parseDistrictMeetingPage({snippets:[{type:"wysiwyg",body:{text:"<p><strong>Data districtsraden en raadscommissies 2026</strong></p><table><tr><th>Data algemene raadscommissie</th><th>Data districtsraad</th></tr><tr><td>maandag 9 november</td><td>maandag 16 november</td></tr></table><p><strong>Data districtsraden en raadscommissies 2027</strong></p><table><tr><th>Data algemene raadscommissie</th><th>Data districtsraad</th></tr><tr><td>maandag 11 januari</td><td>maandag 18 januari</td></tr></table>"}}]});
  assert.deepEqual(parsed.years,[2026,2027]);
  assert.equal(parsed.year,2027);
  assert.deepEqual(parsed.items.map(item=>item.date),["2026-11-09","2026-11-16","2027-01-11","2027-01-18"]);
});

const calendarHtml=`<section><a href="/zittingen/26.1001.0001.0001">districtscollege Antwerpen ma 05/10/2026 - 13:30 Districtshuis Antwerpen - Zaal Christy</a><a href="/zittingen/26.1001.0001.0002">raadscommissie Antwerpen ma 12/10/2026 - 20:00 Provinciehuis Antwerpen</a><a href="/zittingen/26.1001.0001.0003">Bijzondere raadscommissie cultuur, evenementen en feestelijkheden, sport di 13/10/2026 - 20:00 Districtshuis Antwerpen - Zaal Benoit</a><a href="/zittingen/26.1001.0001.0004">districtsraad Antwerpen ma 19/10/2026 - 20:00 Provinciehuis Antwerpen</a></section>`;
test("eBesluit-kalender laat alleen openbare vergaderingen van district Antwerpen door",()=>{const items=parseEbesluitMeetingCalendar(calendarHtml);assert.deepEqual(items.map(item=>[item.title,item.date,item.timeSlot]),[["Raadscommissie Antwerpen","2026-10-12","20:00"],["Bijzondere raadscommissie cultuur, evenementen en feestelijkheden, sport","2026-10-13","20:00"],["Districtsraad Antwerpen","2026-10-19","20:00"]])});
test("eBesluit-maandurls gebruiken expliciet month/year",()=>assert.deepEqual(ebesluitMeetingMonthUrls(new Date("2026-09-30T08:00:00Z"),2),["https://ebesluit.antwerpen.be/zittingen/lijst?month=09&year=2026","https://ebesluit.antwerpen.be/zittingen/lijst?month=10&year=2026"]));
test("fetcher valt terug op eBesluit wanneer de oude jaartabel verdwenen is",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"district-meetings-fallback-"));const noSchedule={currentVersion:"v2",updatedAt:"2026-09-30T08:00:00Z",snippets:[{type:"wysiwyg",body:{text:"<p>Geen planning</p>"}}]};const fetch=async url=>String(url).includes("page-content-by-uuid")?response(noSchedule):{ok:true,status:200,text:async()=>calendarHtml};const s=await run({rootDir:root,clock:()=>new Date("2026-09-30T08:00:00Z"),fetch,log:()=>{}});assert.deepEqual([s[0].fetchStatus,s[0].itemCount],["ok",3]);const doc=JSON.parse(fs.readFileSync(path.join(root,"site","sources","district-vergaderingen.json"),"utf8"));assert.deepEqual(validateSourceDocument(doc,{expectedSourceId:"district-vergaderingen"}),[]);assert.ok(doc.items.every(item=>item.sourceUrl.startsWith("https://ebesluit.antwerpen.be/")))});
