import test from "node:test";
import assert from "node:assert/strict";
import {buildStreetIndex} from "../site/street-core.js";
import {buildDistrictRadar,buildStreetGroups,buildStreetTimeline} from "../site/street-overview.js";
const index=buildStreetIndex([{type:"Feature",properties:{DISTRICT:"ANTWERPEN",LSTRNMID:1,LSTRNM:"Teststraat",RSTRNMID:1,RSTRNM:"Teststraat",postcode:2000},geometry:{type:"LineString",coordinates:[[4.4,51.2],[4.401,51.2]]}}]);
test("straatfiche bundelt live werken, maatregelen en agenda",()=>{const street={id:"1",name:"Teststraat",postcode:"2000"};const groups=buildStreetGroups({works:[{gipodId:11,title:"Werk",status:"In uitvoering",streets:[street]}],publicSpace:[{id:"parking:1",kind:"parking",title:"Parkeerverbod",status:"Goedgekeurd",streets:[street]},{id:"iod:1",kind:"iod",title:"Inname",status:"aanvraag_goedgekeurd",streets:[street]},{id:"sgw:1",kind:"sgw",title:"Werfzone",status:"vergund",streets:[street]}],agendaItems:[{id:"agenda:1",title:"Buurtfeest",date:"2099-01-01",location:"Teststraat 8, 2000 Antwerpen",sourceId:"district-kalender",sourceUrl:"https://www.antwerpen.be/info/x"}],streetIndex:index,asOf:"2098-01-01"});assert.equal(groups.length,1);assert.deepEqual([groups[0].works.length,groups[0].parking.length,groups[0].iod.length,groups[0].sgw.length,groups[0].agenda.length],[1,1,1,1,1])});
test("markt uit stad-markten komt in aparte marktbucket",()=>{const groups=buildStreetGroups({agendaItems:[{id:"markt:1",title:"Gemengde markt",date:"2099-01-01",location:"Teststraat 1, 2000 Antwerpen",sourceId:"stad-markten"}],streetIndex:index,asOf:"2098-01-01"});assert.equal(groups[0].markets.length,1);assert.equal(groups[0].agenda.length,0)});
test("onbetrouwbare agenda-locatie wordt niet gegokt",()=>{const groups=buildStreetGroups({agendaItems:[{id:"agenda:2",title:"Meerdere locaties",date:"2099-01-01",location:"verschillende locaties",sourceId:"district-kalender"}],streetIndex:index,asOf:"2098-01-01"});assert.deepEqual(groups,[])});
test("district-radar telt feitelijke overlap en ernstige hinder",()=>{const a={street:{id:"1",name:"Astraat",postcode:"2000"},works:[{severeHindrance:true}],parking:[{}],iod:[],sgw:[{}],markets:[],agenda:[],changes:[{}],total:3},b={street:{id:"2",name:"Bstraat",postcode:"2000"},works:[],parking:[],iod:[],sgw:[],markets:[{}],agenda:[],changes:[],total:1};const r=buildDistrictRadar([a,b],{layers:{works:{status:"ok"},publicSpace:{status:"ok"}}});assert.equal(r.multiDomainStreets,1);assert.equal(r.workAndTrafficStreets,1);assert.equal(r.severeHindranceStreets,1);assert.equal(r.recentlyChangedStreets,1);assert.equal(r.topOverlap[0].street.name,"Astraat")});
test("radar verbergt wijzigingsaantal bij onbruikbare history",()=>{const r=buildDistrictRadar([],{layers:{works:{status:"error"},publicSpace:{status:"error"}}});assert.equal(r.recentlyChangedStreets,null);assert.equal(r.historyState,"unavailable")});

test("radar vat exact de laatste history-observatie samen",()=>{const groups=[{street:{id:"1",name:"Astraat",postcode:"2000"},works:[],parking:[],iod:[],sgw:[],markets:[],agenda:[],changes:[{type:"added",observedAt:"2026-09-30T05:17:00Z"},{type:"changed",observedAt:"2026-09-30T05:17:00Z"},{type:"removed",observedAt:"2026-09-29T05:17:00Z"}],total:0},{street:{id:"2",name:"Bstraat",postcode:"2000"},works:[],parking:[],iod:[],sgw:[],markets:[],agenda:[],changes:[{type:"removed",observedAt:"2026-09-30T05:17:00Z"}],total:0}];const r=buildDistrictRadar(groups,{observedAt:"2026-09-30T05:17:00Z",layers:{works:{status:"ok"},publicSpace:{status:"ok"}}});assert.deepEqual(r.latestChangeCounts,{added:1,changed:1,removed:1});assert.equal(r.latestChangedStreets,2);assert.equal(r.observedAt,"2026-09-30T05:17:00Z")});
test("radar verbergt de laatste delta wanneer history onbruikbaar is",()=>{const r=buildDistrictRadar([],{observedAt:"2026-09-30T05:17:00Z",layers:{works:{status:"error"},publicSpace:{status:"error"}}});assert.equal(r.latestChangeCounts,null);assert.equal(r.latestChangedStreets,null)});

test("straattijdlijn kijkt tot de verste bekende datum en markeert overlap",()=>{const group={works:[{id:"w",title:"Werk",start:"2026-10-01",end:"2026-10-20"}],parking:[{id:"p",title:"Parkeerverbod",start:"2026-10-05",end:"2026-10-07"}],iod:[],sgw:[{id:"s",title:"Omleiding",start:"2026-10-06",end:"2026-11-15"}],markets:[],agenda:[{id:"a",title:"Buurtfeest",start:"2026-12-20",end:"2026-12-20"}]};const timeline=buildStreetTimeline(group,{asOf:"2026-09-30"});assert.equal(timeline.horizon,"2026-12-20");assert.equal(timeline.peakConcurrent,3);assert.equal(timeline.overlapEntries,3);assert.equal(timeline.entries.at(-1).title,"Buurtfeest")});
test("straattijdlijn laat verlopen items weg maar niet verre toekomst",()=>{const group={works:[{id:"old",title:"Oud",start:"2026-09-01",end:"2026-09-02"},{id:"far",title:"Ver vooruit",start:"2027-08-01",end:"2027-08-05"}],parking:[],iod:[],sgw:[],markets:[],agenda:[]};const timeline=buildStreetTimeline(group,{asOf:"2026-09-30"});assert.deepEqual(timeline.entries.map(item=>item.id),["far"]);assert.equal(timeline.horizon,"2027-08-05")});
